"""changed hotels.locaiton

Revision ID: b70f5e6c94d7
Revises: f54772d83f16
Create Date: 2025-04-27 01:13:46.846716

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b70f5e6c94d7'
down_revision: Union[str, None] = 'f54772d83f16'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hotels', sa.Column('location', sa.String(length=200), nullable=False))
    op.drop_column('hotels', 'locaiton')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hotels', sa.Column('locaiton', sa.VARCHAR(length=200), autoincrement=False, nullable=False))
    op.drop_column('hotels', 'location')
    # ### end Alembic commands ###
