"""hotels add in and out time

Revision ID: 03400733ac70
Revises: 7cf139884380
Create Date: 2025-06-24 21:25:11.662900

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "03400733ac70"
down_revision: Union[str, None] = "7cf139884380"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("bookings", sa.Column("total_price", sa.Float(), nullable=False))
    op.drop_column("bookings", "price")
    op.add_column("hotels", sa.Column("check_in", sa.Time(), nullable=True))
    op.add_column("hotels", sa.Column("check_out", sa.Time(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("hotels", "check_out")
    op.drop_column("hotels", "check_in")
    op.add_column(
        "bookings",
        sa.Column(
            "price",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_column("bookings", "total_price")
    # ### end Alembic commands ###
