"""Rooms

Revision ID: ffebaa9e0b7d
Revises: 41f861581aa5
Create Date: 2025-06-23 21:35:05.410376

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "ffebaa9e0b7d"
down_revision: Union[str, None] = "41f861581aa5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "room_types",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=100), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column("rooms", sa.Column("room_type_id", sa.Integer(), nullable=False))
    op.add_column("rooms", sa.Column("number", sa.Integer(), nullable=False))
    op.create_foreign_key(None, "rooms", "room_types", ["room_type_id"], ["id"])
    op.drop_column("rooms", "quantity")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "rooms",
        sa.Column("quantity", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    op.drop_constraint(None, "rooms", type_="foreignkey")
    op.drop_column("rooms", "number")
    op.drop_column("rooms", "room_type_id")
    op.drop_table("room_types")
    # ### end Alembic commands ###
